def drawp1(n):
    tt.pensize(5)
    tt.up()
    tt.home()
    tt.pd()
    if k==1:
        tt.penup()
        tt.setx(25)
        tt.sety(-44)
        tt.pendown()
        tt.pencolor('green')
        tt.circle(17)
    if k==2:
        tt.penup()
        tt.setx(75)
        tt.sety(-44)
        tt.pendown()
        tt.pencolor('green')
        tt.circle(17)
    if k==3:
        tt.penup()
        tt.setx(125)
        tt.sety(-44)
        tt.pendown()
        tt.pencolor('green')
        tt.circle(17)
    if k==4:
        tt.up()
        tt.setx(25)
        tt.sety(-94)
        tt.pd()
        tt.pencolor('green')
        tt.circle(17)
    if k==5:
        tt.up()
        tt.setx(75)
        tt.sety(-94)
        tt.pd()
        tt.pencolor('green')
        tt.circle(17)
    if k==6:
        tt.penup()
        tt.setx(125)
        tt.sety(-94)
        tt.pd()
        tt.pencolor('green')
        tt.circle(17)
    if k==7:
        tt.up()
        tt.setx(25)
        tt.sety(-144)
        tt.pd()
        tt.pencolor('green')
        tt.circle(17)
    if k==8:
        tt.up()
        tt.setx(75)
        tt.sety(-144)
        tt.pd()
        tt.pencolor('green')
        tt.circle(17)
    if k==9:
        tt.up()
        tt.setx(125)
        tt.sety(-144)
        tt.pd()
        tt.pencolor('green')
        tt.circle(17)
        
def drawp2(n):
    tt.pensize(5)
    tt.seth(0)
    if k==1:
        tt.penup()
        tt.setx(25)
        tt.sety(-25)
        tt.pencolor('red')
        tt.pd()
        tt.right(45)
        tt.right(90)
        tt.forward(23)
        tt.penup()
        tt.setx(25)
        tt.sety(-25)
        tt.right(90)
        tt.penup()
        tt.setx(25)
        tt.sety(-25)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(25)
        tt.sety(-25)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(25)
        tt.sety(-25)
        tt.pd()
        tt.forward(23)
        
    if k==2:
        tt.penup()
        tt.setx(75)
        tt.sety(-25)
        tt.pencolor('red')
        tt.pd()
        tt.right(45)
        tt.right(90)
        tt.forward(23)
        tt.penup()
        tt.setx(75)
        tt.sety(-25)
        tt.right(90)
        tt.penup()
        tt.setx(75)
        tt.sety(-25)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(75)
        tt.sety(-25)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(75)
        tt.sety(-25)
        tt.pd()
        tt.forward(23)
        
    if k==3:
        tt.penup()
        tt.setx(125)
        tt.sety(-25)
        tt.pencolor('red')
        tt.pd()
        tt.right(45)
        tt.right(90)
        tt.forward(23)
        tt.penup()
        tt.setx(125)
        tt.sety(-25)
        tt.right(90)
        tt.penup()
        tt.setx(125)
        tt.sety(-25)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(125)
        tt.sety(-25)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(125)
        tt.sety(-25)
        tt.pd()
        tt.forward(23)
        
    if k==4:
        tt.penup()
        tt.setx(25)
        tt.sety(-75)
        tt.pencolor('red')
        tt.pd()
        tt.right(45)
        tt.right(90)
        tt.forward(23)
        tt.penup()
        tt.setx(25)
        tt.sety(-75)
        tt.right(90)
        tt.penup()
        tt.setx(25)
        tt.sety(-75)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(25)
        tt.sety(-75)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(25)
        tt.sety(-75)
        tt.pd()
        tt.forward(23)
        
    if k==5:
        tt.penup()
        tt.setx(75)
        tt.sety(-75)
        tt.pencolor('red')
        tt.pd()
        tt.right(45)
        tt.right(90)
        tt.forward(23)
        tt.penup()
        tt.setx(75)
        tt.sety(-75)
        tt.right(90)
        tt.penup()
        tt.setx(75)
        tt.sety(-75)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(75)
        tt.sety(-75)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(75)
        tt.sety(-75)
        tt.pd()
        tt.forward(23)
        
        
    if k==6:
        tt.penup()
        tt.setx(125)
        tt.sety(-75)
        tt.pencolor('red')
        tt.pd()
        tt.right(45)
        tt.right(90)
        tt.forward(23)
        tt.penup()
        tt.setx(125)
        tt.sety(-75)
        tt.right(90)
        tt.penup()
        tt.setx(125)
        tt.sety(-75)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(125)
        tt.sety(-75)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(125)
        tt.sety(-75)
        tt.pd()
        tt.forward(23)
        
    if k==7:
        tt.penup()
        tt.setx(25)
        tt.sety(-125)
        tt.pencolor('red')
        tt.pd()
        tt.right(45)
        tt.right(90)
        tt.forward(23)
        tt.penup()
        tt.setx(25)
        tt.sety(-125)
        tt.right(90)
        tt.penup()
        tt.setx(25)
        tt.sety(-125)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(25)
        tt.sety(-125)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(25)
        tt.sety(-125)
        tt.pd()
        tt.forward(23)
        
    if k==8:
        tt.penup()
        tt.setx(75)
        tt.sety(-125)
        tt.pencolor('red')
        tt.pd()
        tt.right(45)
        tt.right(90)
        tt.forward(23)
        tt.penup()
        tt.setx(75)
        tt.sety(-125)
        tt.right(90)
        tt.penup()
        tt.setx(75)
        tt.sety(-125)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(75)
        tt.sety(-125)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(75)
        tt.sety(-125)
        tt.pd()
        tt.forward(23)
        
    if k==9:
        tt.penup()
        tt.setx(125)
        tt.sety(-125)
        tt.pencolor('red')
        tt.pd()
        tt.right(45)
        tt.right(90)
        tt.forward(23)
        tt.penup()
        tt.setx(125)
        tt.sety(-125)
        tt.right(90)
        tt.penup()
        tt.setx(125)
        tt.sety(-125)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(125)
        tt.sety(-125)
        tt.pd()
        tt.forward(23)
        tt.right(90)
        tt.penup()
        tt.setx(125)
        tt.sety(-125)
        tt.pd()
        tt.forward(23)

while(True):
    import turtle as t
    #sc=t.Screen()
    tt=t.Turtle()
    tt.ht()
    t.ht()
    t.speed(500)
    tt.speed(3)
    kk=t.Turtle()
    ps1=0
    ps2=0
    t.forward(150)
    t.right(90)
    t.forward(150)
    t.right(90)
    t.forward(150)
    t.right(90)
    t.forward(150)
    t.right(180)
    t.setx(50)
    t.forward(150)
    t.right(180)
    t.setx(100)
    t.forward(150)
    t.setx(150)
    t.right(180)
    t.forward(50)
    t.right(90)
    t.forward(150)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(150)
    '''kk=int(input())
    t.forward(kk)'''
    p1=[]
    p2=[]
    p=[]
    c=0
    ff=0
    while(c<9):
        kk.pensize(7)
        kk.ht()
        t.up()
        kk.speed(1)
        if 1 in p1 and 2 in p1 and 3 in p1:
            kk.penup()
            kk.setx(-15)
            kk.sety(-25)
            kk.setheading(0)
            kk.pd()
            kk.forward(175)
            t.clear()
            tt.clear()
            kk.clear()
            t.write(" PLAYER 1 WINS ",True,align='right',font=('Arial',25,'normal'))
            break
        
        elif 4 in p1 and 5 in p1 and 6 in p1:
            kk.penup()
            kk.setx(-15)
            kk.sety(-75)
            kk.setheading(0)
            kk.pd()
            kk.forward(175)
            t.clear()
            tt.clear()
            kk.clear()
            t.write(" PLAYER 1 WINS ",True,align='right',font=('Arial',25,'normal'))
            break
        elif 7 in p1 and 8 in p1 and 9 in p1:
            kk.penup()
            kk.setx(-15)
            kk.sety(-125)
            kk.setheading(0)
            kk.pd()
            kk.forward(175)
            t.clear()
            tt.clear()
            kk.clear()
            t.write(" PLAYER 1 WINS ",True,align='right',font=('Arial',25,'normal'))
            break
        elif 7 in p1 and 4 in p1 and 1 in p1:
            kk.penup()
            kk.setx(25)
            kk.sety(15)
            kk.setheading(0)
            kk.right(90)
            kk.pd()
            kk.forward(175)
            t.clear()
            tt.clear()
            kk.clear()
            t.write(" PLAYER 1 WINS ",True,align='right',font=('Arial',25,'normal'))
            break
        elif 8 in p1 and 5 in p1 and 2 in p1:
            kk.penup()
            kk.setx(75)
            kk.sety(15)
            kk.setheading(0)
            kk.right(90)
            kk.pd()
            kk.forward(175)
            t.clear()
            tt.clear()
            kk.clear()
            t.write(" PLAYER 1 WINS ",True,align='right',font=('Arial',25,'normal'))
            break
        elif 9 in p1 and 3 in p1 and 6 in p1:
            kk.penup()
            kk.setx(125)
            kk.sety(15)
            kk.setheading(0)
            kk.right(90)
            kk.pd()
            kk.forward(175)
            t.up()
            t.clear()
            tt.clear()
            t.write(" PLAYER 1 WINS ",True,align='right',font=('Arial',25,'normal'))
            break
        elif 7 in p1 and 5 in p1 and 3 in p1:
            kk.penup()
            kk.setx(165)
            kk.sety(15)
            kk.setheading(225)
            kk.pd()
            kk.forward(250)
            t.clear()
            tt.clear()
            kk.clear()
            t.write(" PLAYER 1 WINS ",True,align='right',font=('Arial',25,'normal'))
            break
        elif 9 in p1 and 5 in p1 and 1 in p1:
            kk.penup()
            kk.setx(-15)
            kk.sety(15)
            kk.setheading(315)
            kk.pd()
            kk.forward(250)
            t.clear()
            tt.clear()
            kk.clear()
            t.write(" PLAYER 1 WINS ",True,align='right',font=('Arial',25,'normal'))
            break
        elif 1 in p2 and 2 in p2 and 3 in p2:
            kk.penup()
            kk.setx(-15)
            kk.sety(-25)
            kk.setheading(0)
            kk.pd()
            kk.forward(175)
            t.clear()
            tt.clear()
            kk.clear()
            t.write(" PLAYER 2 WINS ",True,align='right',font=('Arial',25,'normal'))
            break
        elif 4 in p2 and 5 in p2 and 6 in p2:
            kk.penup()
            kk.setx(-15)
            kk.sety(-75)
            kk.setheading(0)
            kk.pd()
            kk.forward(175)
            kk.clear()
            t.write("  PLAYER 2 WINS",True,align='right',font=('Arial',25,'normal'))
            break
        elif 7 in p2 and 8 in p2 and 9 in p2:
            kk.penup()
            kk.setx(-15)
            kk.sety(-125)
            kk.setheading(0)
            kk.pd()
            kk.forward(175)
            t.clear()
            tt.clear()
            kk.clear()
            t.write("  PLAYER 2 WINS ",True,align='right',font=('Arial',25,'normal'))
            break
        elif 7 in p2 and 4 in p2 and 1 in p2:
            kk.penup()
            kk.setx(25)
            kk.sety(15)
            kk.setheading(0)
            kk.right(90)
            kk.pd()
            kk.forward(175)
            t.clear()
            tt.clear()
            kk.clear()
            t.write("  PLAYER 2 WINS ",True,align='right',font=('Arial',25,'normal'))
            break
        elif 8 in p2 and 5 in p2 and 2 in p2:
            kk.penup()
            kk.setx(75)
            kk.sety(15)
            kk.setheading(0)
            kk.right(90)
            kk.pd()
            kk.forward(175)
            t.clear()
            tt.clear()
            kk.clear()
            t.write("  PLAYER 2 WINS",True,align='right',font=('Arial',25,'normal'))
            break
        elif 9 in p2 and 3 in p2 and 6 in p2:
            kk.penup()
            kk.setx(125)
            kk.sety(15)
            kk.setheading(0)
            kk.right(90)
            kk.pd()

            kk.forward(175)
            t.clear()
            tt.clear()
            kk.clear()
            t.write("  PLAYER 2 WINS ",True,align='right',font=('Arial',25,'normal'))
            break
        elif 7 in p2 and 5 in p2 and 3 in p2:
            kk.penup()
            kk.setx(165)
            kk.sety(15)
            kk.setheading(225)
            kk.pd()
            kk.forward(250)
            t.clear()
            tt.clear()
            kk.clear()
            t.write("  PLAYER 2 WINS ",True,align='right',font=('Arial',25,'normal'))
            break
        elif 9 in p2 and 5 in p2 and 1 in p2:
            kk.penup()
            kk.setx(-15)
            kk.sety(15)
            kk.setheading(315)
            kk.pd()
            kk.forward(250)
            t.clear()
            tt.clear()
            kk.clear()
            t.write(" PLAYER 2 WINS ",True,align='right',font=('Arial',25,'normal'))
            break
        else:
            ff=1

        if c%2==0:
            k=t.numinput("player 1 ","enter choice")
            if k in p1 or k in p2:
                continue
            p1.append(k)
            p.append(k)
            drawp1(k)
        else:
            k=t.numinput("player 2 ","enter choice")
            if k in p1 or k in p2:
                continue
            p2.append(k)
            p.append(k)
            drawp2(k)
            
        c+=1 
    if c==9:
        t.clear()
        tt.clear()
        kk.clear()
        t.write(" TIE ",True,align='right',font=('Arial',25,'normal'))
        t.clear()
        t3=t.numinput("enter choice","play again : 1\quit : 2")
        if t3==1:
            continue
        elif t3==2:
            break
    else:
        t.clear()
        t3=t.numinput("enter choice","play again : 1\nquit : 2")
        if t3==1:
            continue
        elif t3==2:
            break
        
        
        





